import Head from "next/head";
import Banner from "../components/banner/banner";
import Navbar from "../components/nav/navbar";
import SectionCards from "../components/card/secion-cards";
import styles from "../styles/Home.module.css";
import { getPopularVideos, getVideos } from "../lib/videos";
import { useContext } from "react";
import { UserContext } from "../context/UserContext";

export async function getServerSideProps() {
  const disneyVideos = await getVideos({ searchQuery: "disney trailer" });
  const travelVideos = await getVideos({ searchQuery: "travel" });
  const productivityVideos = await getVideos({ searchQuery: "productivity" });
  const popularVideos = await getPopularVideos();

  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos },
  };
}

export default function Home({
  disneyVideos,
  travelVideos,
  productivityVideos,
  popularVideos,
}) {
  const { user, setUser } = useContext(UserContext);

  return (
    <div className={styles.homeContainer}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        {/* <Navbar username={user?.email} /> */}

        <Banner
          title={"Clifford the red dog"}
          subTitle={"A very cute dog"}
          imageUrl={"/static/clifford.webp"}
          videoId={"4zH5iYM4wJo"}
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title={"Disney"} videos={disneyVideos} size={"large"} />

          <SectionCards title={"Travel"} videos={travelVideos} size={"small"} />

          <SectionCards
            title={"Productivity"}
            videos={productivityVideos}
            size={"medium"}
          />

          <SectionCards
            title={"Popular"}
            videos={popularVideos}
            size={"small"}
          />
        </div>
      </div>
    </div>
  );
}
